(use judge)
(import stx)

(test (stx/name (stx/new "t" 1 1 {})) "t")
(test (stx/line (stx/new "t" 3 7 {})) 3)
(test (stx/column (stx/new "t" 3 7 {})) 7)
(test (stx/value (stx/new "t" 3 7 {})) {})
(test (stx/line (stx/new "t" math/int32-max 7 {})) 2147483647)
(test-error (stx/line (stx/new "t" (inc math/int32-max) 7 {}))
            "bad slot #1, expected 32 bit signed integer, got 2147483648")
(test-error (stx/line (stx/new "t" 7 (inc math/int32-max) {}))
            "bad slot #2, expected 32 bit signed integer, got 2147483648")

(test (stx/name (unmarshal (marshal (stx/new "j" 4 6 {})))) "j")
(test (stx/line (unmarshal (marshal (stx/new "j" 4 6 {})))) 4)
(test (stx/column (unmarshal (marshal (stx/new "j" 4 6 {})))) 6)
(test (stx/value (unmarshal (marshal (stx/new "j" 4 6 {})))) {})
